version: '3.4'

services:
  discordbotapplication:
    image: ${DOCKER_REGISTRY-}jaguar
    build:
      context: .
      dockerfile: Jaguar/Dockerfile
    depends_on:
      - mongo
    environment:
      DISCORDBOT_Discord__Token: ${DISCORDBOT_Discord__Token}
      ASPNETCORE_ENVIRONMENT: 'Development'
      DISCORDBOT_Espn__Cookie: ${DISCORDBOT_Espn__Cookie}
      DISCORDBOT_ConnectionStrings__MongoDB: ${DISCORDBOT_ConnectionStrings__MongoDB}
  mongo:
    image: mongo
    ports:
    - "27017:27017"